"""empty message

Revision ID: ab7282125484
Revises: c06ee2553548
Create Date: 2020-09-10 11:54:48.895652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7282125484'
down_revision = 'c06ee2553548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('postId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'articl', ['postId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'articl', ['slug'], ['id'])
    op.drop_column('tag', 'postId')
    # ### end Alembic commands ###
